### PR TITLE
Added gamma correction for better color accuracy

### PR DESCRIPTION
**Pull request by makzdot**
I don't think we're there yet but I believe this changes gives a little bit more accurate colors.

### CODE REVIEW

**Comment by corbanmailloux** [comment]
For reference, this is related to #16.

**Review by corbanmailloux — COMMENTED** [review]
I'd like to expose a configuration option to enable or disable this new code. 
Could you add a boolean option in the config file called something like `CONFIG_USE_GAMMA_CORRECTION`, and then an `if` check in `setColor`?

**Comment by makzdot** [comment]
Good idea. Don't know when I'll get around to this. I hope somewhere this week or next weekend.

**Comment by r41d** [comment]
TODO: adapt to the new unified sketch

**Comment by corbanmailloux** [comment]
I'm going to close this PR for now. If you'd like to update this in the future, please feel free to reopening.

**Pull request closed without merging**
